quotes = ("The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.",
          "It is our choices, Harry, that show what we truly are, far more than our abilities.",
          "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
          "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.",
          "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
          "Try not to become a man of success. Rather become a man of value.",
          "It is better to be hated for what you are than to be loved for what you are not.",
          "I have not failed. I've just found 10,000 ways that won't work.",
          "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
          "A day without sunshine is like, you know, night.",
          "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
          "If you can't explain it to a six year old, you don't understand it yourself.",
          "I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.",
          "I may not have gone where I intended to go, but I think I have ended up where I needed to be.",
          "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.",
          "It is not a lack of love, but a lack of friendship that makes unhappy marriages.")